spring:
  datasource:
    url: jdbc:mysql://localhost:3000/${DB_NAME}
    username: ${USER_NAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true